Created a test folder Find and rootFolderTest which contains files wh…
nyuoss/project-gitignore pull request #2
Opened 2024-04-24 21:41 UTC by utsav-sharma2020

…ich may/maynot be ignored. The MainAttempt.java is the program which runs the feature of gitignore

Please ensure your pull request adheres to the following guidelines:

- **Title**: A brief, descriptive summary of your changes.
- **Description**: Explain the changes you've made and why you've made them.
- **Branch Naming**: Prefix the type of change in the branch name and/or select the option relevant:
  - [ ] `chore/` This change requires a documentation update
  - [ ] Bug fix `bugfix/` (non-breaking change which fixes an issue)
  - [ ] New feature `feature/` (non-breaking change which adds functionality)
  - [ ] Breaking change `fix/` (fix or feature that would cause existing functionality to not work as expected)
- **Related Issue(s)**: Mention any issues that are related to these changes.
- **Testing**: Detail the testing that was done to validate the changes.
- **Checklist**:
  - [ ] I have performed a self-review of my own code.
  - [ ] I have added tests that prove my fix is effective or that my feature works.
- **Screenshots/Output**: Include any relevant screenshots or output demonstrating the changes (if applicable).
- **Additional Notes**: Any further comments or notes for the reviewers.

2024-04-26 17:36 UTC, tanmayr71 requested changes
Code looks good, can you remove the .DS_Store files annd create a draft again? Thanks!

2024-04-29 04:31 UTC, Hao-191 reviewed
looks good

2024-05-01 00:19 UTC, sash7410 commented on src/main/java/Find/.DS_Store
Can we not push .DS_Store files?

2024-05-01 00:19 UTC, sash7410 commented on src/main/java/.DS_Store
Can we not push .DS_Store files?

2024-05-01 00:25 UTC, sash7410 commented
LGTM , just delete .DSstore files

2024-05-01 00:26 UTC, nt591 commented
Likely you'll need to update the .gitignore file in the repo to avoid this from uploading in the future.

2024-05-01 00:35 UTC, slachitoff reviewed
I agree with the previous comments. Apart from adding the .DS_Store files to the .gitignore, the code itself looks good for now.

2024-05-01 00:40 UTC, sash7410 commented
I have added the .DS_Store in the gitignore file in the new PR I made, can we merge that branch?

2024-05-08 21:06 UTC, tanmayr71 commented
Should we close this PR? This work has been done by @Hao-191 
@utsav-sharma2020 - Can you check the work the work done already and see if we need this commit?

2024-05-09 02:03 UTC, closed without merging